disabled_rules: # rule identifiers to exclude from running
- identifier_name
- function_parameter_count

opt_in_rules: # some rules are only opt-in
- control_statement
- empty_count
- trailing_newline
- colon
- comma

included: # paths to include during linting. `--path` is ignored if present.
- CapstoneProject

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly

force_try:
  severity: warning # explicitly
  
line_length: 150

# they can set both implicitly with an array
type_body_length:
- 300 # warning
- 400 # error

file_length:
  warning: 500
  error: 800